import './make-user-test.js';
import './create-quest-link.test.js';
import './create-completed-quest.test.js';
import './api-test.js';
import './create-choice.test.js';
import './has-completed-all-quests.test.js';
import './is-dead.test.js';
import './score-army.test.js';
import './score-morale.test.js';